// Generated by IcedCoffeeScript 1.3.3f
(function() {
  var $, app, buildingaddress, buildingdata, buildingname, classdata, classes, classlist, classlist_set, everyone, express, fs, getCalendarId, http, httpserver, iced, line, location_addresses, location_list, nowjs, request, restler, subjectnum, __iced_k, __iced_k_noop, _i, _j, _len, _len1, _ref, _ref1, _ref2;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  fs = require('fs');

  request = require('request');

  $ = require('jQuery');

  restler = require('restler');

  express = require('express');

  app = express();

  http = require('http');

  httpserver = http.createServer(app);

  httpserver.listen(3333);

  nowjs = require('now');

  everyone = nowjs.initialize(httpserver);

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('view engine', 'ejs');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.set('view options', {
      layout: false
    });
    app.locals({
      layout: false
    });
    return app.use(express["static"](__dirname + '/'));
  });

  classes = {};

  classlist = [];

  classlist_set = {};

  classdata = fs.readFileSync('classes.txt', 'utf-8');

  _ref = classdata.split('\n');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    line = _ref[_i];
    if (line.indexOf('\t') === -1) continue;
    subjectnum = line.split('\t')[0];
    if (!(classlist_set[subjectnum] != null)) {
      classlist_set[subjectnum] = true;
      classlist.push(subjectnum);
    }
  }

  classlist.sort();

  buildingdata = fs.readFileSync('buildings.txt', 'utf-8');

  location_list = [];

  location_addresses = {};

  _ref1 = buildingdata.split('\n');
  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
    line = _ref1[_j];
    _ref2 = line.split('\t'), buildingname = _ref2[0], buildingaddress = _ref2[1];
    location_list.push(buildingname);
    location_addresses[buildingname] = buildingaddress;
  }

  everyone.now.location_list = location_list;

  everyone.now.location_addresses = location_addresses;

  everyone.now.addClassType = function(classname) {
    if (typeof classname !== typeof '') return;
    if (!(classlist_set[classname] != null)) {
      classlist_set[classname] = true;
      classlist.push(classname);
      return classlist.sort();
    }
  };

  everyone.now.getClassesWithPrefix = function(prefix, callback) {
    var matches, x;
    matches = (function() {
      var _k, _len2, _results;
      _results = [];
      for (_k = 0, _len2 = classlist.length; _k < _len2; _k++) {
        x = classlist[_k];
        if (x.indexOf(prefix) === 0) _results.push(x);
      }
      return _results;
    })();
    return callback(matches);
  };

  everyone.now.getCalendarId = getCalendarId = function(classname, callback) {
    return restler.get('http://localhost:5000/calid?title=' + classname).on('complete', callback);
  };

  root.classids = {};

  everyone.now.getCalendarIds = function(classnames, callback) {
    var i, title, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    (function(__iced_k) {
      var _k, _len2;
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "app.coffee",
        funcname: "getCalendarIds"
      });
      for (i = _k = 0, _len2 = classnames.length; _k < _len2; i = ++_k) {
        title = classnames[i];
        if (!(root.classids[title] != null)) {
          getCalendarId(title, __iced_deferrals.defer({
            assign_fn: (function(__slot_1, __slot_2) {
              return function() {
                return __slot_1[__slot_2] = arguments[0];
              };
            })(classids, title),
            lineno: 74
          }));
        }
      }
      __iced_deferrals._fulfill();
    })(function() {
      return callback(root.classids);
    });
  };

  everyone.now.getClasses = function(username, callback) {
    if (!(classes[username] != null)) classes[username] = [];
    if (callback != null) return callback(classes[username]);
  };

  everyone.now.addClass = function(username, classname, callback) {
    if (!(classes[username] != null)) classes[username] = [];
    if (classes[username].indexOf(classname) === -1) {
      classes[username].push(classname);
    }
    if (callback != null) return callback(classes[username]);
  };

  everyone.now.removeClass = function(username, classname, callback) {
    var x;
    if (!(classes[username] != null)) classes[username] = [];
    classes[username] = (function() {
      var _k, _len2, _ref3, _results;
      _ref3 = classes[username];
      _results = [];
      for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
        x = _ref3[_k];
        if (x !== classname) _results.push(x);
      }
      return _results;
    })();
    if (callback != null) return callback(classes[username]);
  };

}).call(this);
